#Done by	Ovidiu - Dan Bogat

CFLAGS=-Wall -g -O2
CC=cc
LIBS=
BINDIR=./../bin

SOURCEFILES=main.C functions.C
HEADERS=main.H functions.H debug.H


all inte: $(SOURCEFILES) $(HEADERS)
	$(CC) $(CFLAGS) $(SOURCEFILES) -o $(BINDIR)/inte $(LIBS)
